example = function() {
  library(repboxRun)
  artid = "aejpol_3_4_8"
  artid = "aejmic_6_3_9"
  projects.dir = "~/repbox/projects_reg"
  repbox_init_ejd_project(artid=artid, projects.dir=projects.dir)


  project_dir = "C:/libraries/repbox/projects_reg/testr"
  steps = repbox_steps_from(static_code=TRUE, art=FALSE)
  repbox_run_project(project_dir,lang=NULL, steps=steps)
  rstudioapi::filesPaneNavigate(project_dir)


  project_dir = "/home/rstudio/repbox/projects_reg/testsupp"

  steps = repbox_run_steps_from(static_code=TRUE, art=FALSE, reproduction = FALSE)
  repbox_run_project(project_dir, steps=steps)

  library(repboxRun)
  project_dir = "/home/rstudio/repbox/projects_reg/aejmac_6_3_1"
  project_dir = "/home/rstudio/repbox/projects_reg/testsupp"
  project_dir = "/home/rstudio/repbox/projects_reg/aejpol_3_4_8"
  project_dir = "/home/rstudio/repbox/projects_reg/aejpol_7_2_11"

  #steps = repbox_run_steps_from(art = TRUE)
  #restorepoint::restore.point.options(display.restore.point = !TRUE)
  steps = repbox_run_steps_from(reproduction =  TRUE,map=TRUE)
  opts = repbox_run_opts(art_opts = repbox_art_opts(overwrite=TRUE), html_opts = repbox_html_opts(add_art_source_tab = TRUE))
  repbox_run_project(project_dir, steps=steps, opts=opts)

  rstudioapi::filesPaneNavigate(project_dir)

}

#' @title Run repbox analysis for a project (article with supplement)
#'
#' @param project_dir Path to project directory
#' @param lang Language(s) to run analysis for can be any subset of c("r","stata")
#' @param steps Vector of analysis steps to run. Use repbox_steps_from function to create this.
#' @param opts Options for analysis steps generated by repbox_run_opts function.
#' @export
repbox_run_project = function(project_dir, lang = c("stata","r")[1], steps = repbox_steps_all(), opts = repbox_run_opts()) {
  restore.point("repbox_run_project")

  options(dplyr.summarise.inform = FALSE)

  if (!dir.exists(project_dir)) {
    cat("\nProject directory", project_dir, "does not exist!\n")
    return(invisible(FALSE))
  }
  dap.file = paste0(project_dir,"/metareg/dap/stata/dap.Rds")

  show_title = function(str) {
    cat("\n++++++++++++++++++++++++++++++++++++++++++++++++++++\n",str,"\n+++++++++++++++++++++++++++++++++++++++++++++++++++++\n")
  }

  org.dir = file.path(project_dir,"org")
  sup.dir = file.path(project_dir,"mod")
  repbox.dir = file.path(project_dir, "repbox")
  repbox.stata.dir = file.path(project_dir, "repbox/stata")
  repbox.r.dir = file.path(project_dir, "repbox/r")

  parcels = list(.files = list())

  if (steps$file_info) {
    parcels$.files$org = make.project.files.info(project_dir,for.org=TRUE, for.mod = FALSE)$org
  }

  if (steps$static_code) {
    show_title("Static analysis of code and its comments")
    repbox_log_step_start(project_dir, "static_code", opts)

    if (!dir.exists(repbox.dir)) dir.create(repbox.dir)

    # Create file info from /org folder
    parcels$.files$org = make.project.files.info(project_dir,for.org=TRUE, for.mod = FALSE)$org
    # Save script content in Rds files in parcels
    parcels = repbox_make_script_parcel(project_dir, parcels)
    if ("stata" %in% lang) {
      cat("\n  Stata static code analysis...\n\n")
      parcels = repbox_stata_static_parcel(project_dir, parcels=parcels)
      parcels = repboxCodeText::code_project_find_refs(project_dir, parcels=parcels)
    }
    if ("r" %in% lang) {
      cat("\n  R static code analysis...\n\n")
      parcels = repboxR::repbox_project_static_analyse_r(project_dir,parcels=parcels, opts=opts$r_opts)
    }

    repbox_log_step_end(project_dir, "static_code")
  }


  if (steps$art) {
    show_title("Extract information from article text")
    repbox_log_step_start(project_dir, "art", opts)
    art_update_project(project_dir, opts=opts$art_opts)
    repbox_log_step_end(project_dir, "art")
  }

  # If we run the reproduction step again, we will clear most results
  if (steps$reproduction) {
    show_title("Reproduction of initial supplement")
    repbox_log_step_start(project_dir, "reproduction", opts)

    if (dir.exists(sup.dir)) remove.dir(sup.dir)
    # Keep file dates so that we can better
    # see which files are overwritten when comparing
    # original to modified supplement
    copy.dir(org.dir, sup.dir,copy.date=TRUE)
    unzip.zips(sup.dir)

    make.project.files.info(project_dir, for.mod = TRUE, for.org=TRUE)

    # Remove all files except for code files in org folder
    if (opts$slimify_org) {
      slimify.org.dir(project_dir)
    }


    if ("stata" %in% lang) {
      remove.dir(repbox.stata.dir)
      dir.create(repbox.stata.dir)

      dap_and_cache_remove_from_project(project_dir)
      res = repbox_project_run_stata(project_dir,opts=opts$stata_opts)
    }
    if ("r" %in% lang) {
      parcels = repbox_project_run_r(project_dir, opts=opts$r_opts,parcels = parcels)
      parcels = repbox_project_extract_r_results(project_dir, parcels, opts=opts$r_opts)
    }
    make.project.files.info(project_dir, for.mod = TRUE, for.org=FALSE)
    repbox_log_step_end(project_dir, "reproduction")
  }

  if (steps$reg & "stata" %in% lang) {
    show_title("Rerun Stata scripts to extract regression information")
    repbox_log_step_start(project_dir, "reg", opts)
    dap = get.project.dap(project_dir, make.if.missing = TRUE)

    if (opts$store_data_caches) {
      cache.dir = file.path(project_dir, "metareg/dap/stata/cache")
      if (!dir.exists(cache.dir)) dir.create(cache.dir,recursive = TRUE)
      store.data = dap.to.store.data(dap, cache.dir)
    } else {
      store.data = NULL
    }

    if (dir.exists(sup.dir)) remove.dir(sup.dir)
    copy.dir(org.dir, sup.dir,copy.date=TRUE)
    unzip.zips(sup.dir)

    stata_opts = opts$stata_opts
    stata_opts$extract.reg.info = TRUE
    stata_opts$store.data = store.data
    res = repbox_project_run_stata(project_dir,opts=stata_opts)
    repbox_log_step_end(project_dir, "reg")
  }

  if (steps$mr_base & "stata" %in% lang) {
    show_title("Base Metareg")
    repbox_log_step_start(project_dir, "mr_base", opts)
    res = mr_base_run_study(project_dir, stop.on.error = opts$stop.on.error,create.repdb = TRUE,stata_version = opts$stata_version)
    repbox_log_step_end(project_dir, "mr_base")
  }

  parcels = NULL
  if (steps$repbox_repdb) {
    show_title("Store repbox repdb")
    repbox_log_step_start(project_dir, "repbox_repdb", opts)
    parcels = repbox_to_repdb(project_dir)
    repbox_log_step_end(project_dir, "repbox_repdb")
  }



  if (steps$map) {
    show_title("Create Mappings")
    repbox_log_step_start(project_dir, "map", opts)
    parcels = repboxMap::map_repbox_project(project_dir,parcels = parcels, opts = opts$map_opts)
    repbox_log_step_end(project_dir, "map")
  }

  if (steps$html) {
    show_title("Create HTML Reports")
    repbox_log_step_start(project_dir, "html", opts)
    repboxHtml::repbox_project_html(project_dir,lang=lang,parcels = parcels, opts = opts$html_opts)
    repbox_log_step_end(project_dir, "html")
  }
  return(TRUE)
}

repbox_log_step_start = function(project_dir, step, opts) {
  step.info.dir = file.path(project_dir,"steps")
  if (!dir.exists(step.info.dir)) dir.create(step.info.dir, recursive = TRUE)
  file = paste0(step.info.dir, "/",step,".start.Rds")
  saveRDS(list(start_time=Sys.time(), opts=opts), file)
}

repbox_log_step_end = function(project_dir, step) {
  step.info.dir = file.path(project_dir,"steps")
  file = paste0(step.info.dir, "/",step,".end.Rds")
  saveRDS(list(end_time = Sys.time()), file)
}
